server:
  port: 8091
  tomcat:
    threads:
      max: 50
    accept-count: 50
    max-connections: 100
#  sentinel:
#    enabled: true
hm:
  db:
    database: hm-comment
  swagger:
    title: "黑马商城评论服务接口文档"
    package: com.hmall.comment.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
